#
# Makefile for libgeptree.so
#


LIBRARY = Tree

SRC  = tree.cpp \
       tree_executer.cpp \
       tree_function.cpp \
       tree_value.cpp

INCS = GEPTree.hpp \
       GEPTreeExecuter.hpp \
       GEPTreeFunction.hpp \
       GEPTreeValue.hpp

LIBS =

TEST_SRC = test_function_tree.cpp

clean: library-clean

include ../../Makefile.include
-include .depend
